modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/CGessinger/Creatures-And-Beasts-Minecraft-Mod/issues"
[[mods]]
modId="cnb"
version="${file.jarVersion}"
displayName="Creatures and Beasts"
updateJSONURL="http://myurl.me/"
displayURL="https://github.com/CGessinger/Creatures-And-Beasts-Minecraft-Mod"
logoFile="logo.png"
credits="Thanks for this minecraft mod goes to the authors, Azure Doom, and everyone who contributed to the project"
authors="Joosh, CGessinger"
description='''
This is a simple minecraft mod which adds tons of new creatures. It is designed to make minecraft feel more alive and enhance the survival experience!
'''
[[dependencies.cnb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.cnb]]
    modId="geckolib3"
    mandatory=true
    versionRange="3.0.0-beta.8,"
    ordering="BEFORE"
    side="BOTH"
