modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/CGessinger/Creatures_And_Beasts-Forge/issues"
[[mods]]
modId="cnb"
version="${file.jarVersion}"
displayName="Creatures and Beasts"
updateJSONURL="http://myurl.me/"
displayURL="https://github.com/CGessinger/Creatures_And_Beasts-Forge"
logoFile="logo.png"
credits="Thanks for this minecraft mod goes to the authors, Azure Doom, and everyone who contributed to the project"
authors="Joosh, CGessinger"
description='''
Creatures and Beasts is a vanilla-style creature mod which fills each biome with new mobs, from the oceans of the overworld to the void of the end
'''
[[dependencies.cnb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cnb]]
    modId="geckolib3"
    mandatory=true
    versionRange="3.0.0-beta.8,"
    ordering="BEFORE"
    side="BOTH"
